// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD5FexF-m_27zM5hvslTLTuQg9s9_Zq2Xc',
    appId: '1:455605879614:web:c50d86e319dae77627226f',
    messagingSenderId: '455605879614',
    projectId: 'beauty-spa-8e606',
    authDomain: 'beauty-spa-8e606.firebaseapp.com',
    storageBucket: 'beauty-spa-8e606.appspot.com',
    measurementId: 'G-HHLPTRKZED',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB6Zbmin3dCLOZFIDO0NeMnDXEdCkV-1nY',
    appId: '1:455605879614:android:53345e69a4f354ea27226f',
    messagingSenderId: '455605879614',
    projectId: 'beauty-spa-8e606',
    storageBucket: 'beauty-spa-8e606.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAMscOC1RzxYPsJJAkfUx354UCmBZhqkn8',
    appId: '1:455605879614:ios:2c9936d2bdcc6d4327226f',
    messagingSenderId: '455605879614',
    projectId: 'beauty-spa-8e606',
    storageBucket: 'beauty-spa-8e606.appspot.com',
    iosClientId: '455605879614-23q0rf9h9k5034qf1sv4ke6e27n4b73p.apps.googleusercontent.com',
    iosBundleId: 'com.example.beautySpa',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAMscOC1RzxYPsJJAkfUx354UCmBZhqkn8',
    appId: '1:455605879614:ios:2c9936d2bdcc6d4327226f',
    messagingSenderId: '455605879614',
    projectId: 'beauty-spa-8e606',
    storageBucket: 'beauty-spa-8e606.appspot.com',
    iosClientId: '455605879614-23q0rf9h9k5034qf1sv4ke6e27n4b73p.apps.googleusercontent.com',
    iosBundleId: 'com.example.beautySpa',
  );
}
